
# (PART) Thinking {-}

# Power of what?

What quantity within your model do you wish to calculate power for? Overall model goodness-of-fit, individual parameters, or combinations of parameters? The first step is always to think about what you want to achieve with the power analysis, and for that you must answer the question, "power of what?".


## Simple linear regression

### Step 1: model specification

Write down the regression model of interest, including all variables and parameters:

$$
bpsystol = \beta_0 + \beta_1(age) + \beta_2(sex) + \beta_3(age*sex) + \epsilon
$$

In this case, the data are from the National Health and Nutrition Examination Survey (`NHANES`) (<https://www.cdc.gov/nchs/nhanes/index.htm>) and the variables of interest are `bpsystol` (systolic blood pressure), `age`, `sex`, and their interaction, and the parameters of interest are $\beta_0$, $\beta_1$, $\beta_2$, $\beta_3$.

### Step 2: Variable composition

Specify the details of the covariates, such as the range of `age` or the proportion of females (`sex`). For example, the range of `age` might encompass the full range of human longevity (e.g., 0 to 120 years) or could be more focused on non-retired adults (e.g., 18 to 65 years). The proportion of females could theoretically vary anywhere in the interval (0, 1), but practically is rarely outside of the interval [0.45, 0.55].

### Step 3: Parameter composition

Locate or think about reasonable values for the parameters in your model. You may draw on your own, or your colleague's, substantive expertise about the phenomenom you're studying to determine what paramater values are plausible. Or, you might look to the literature for studies that examined similar effects and use these as a starting point.


## Mixed effects model

### Step 1: model specification

Write down the regression model of interest, including all variables and parameters:

$$
weight_{it} = \beta_0 + \beta_1(age_{it}) + \beta_2(female_i) + \beta_3(age_{it}*female_i) + \mu_{0i} + \mu_{1i}(age) + \epsilon_{it}
$$

where $i$ stands for `children`, $t$ for `age`, and we assume $\mu_{0i} \sim N(0, \tau_0)$, $\mu_{1i}\sim N(0, \tau_1)$, $\epsilon_{it} \sim N(0, \sigma)$.

The covariates are `weight`, `age`, `female`, and the interaction term `age\*female`. Also, we need to estimate the coefficients for $\beta_0$ (Intercept), $\beta_1$ (coefficient for age), $\beta_2$ (coefficient for the female comparing with the male), $\beta_3$ (coefficient for the interaction), $\mu_{1i}$ (random effect of age).

We also need to think about the covariates in our model. This is a longitudinal study, so we need to specify the starting age, the length of time between measurements, and the total number of measurements. We also need to consider the proportion of males and females in our study. Are we likely to sample 50% females and 50% males?

Let's assume that we will measure the childrens' weight every 6 months for 2 years beginning at age 12. And let's also assume that the sample will be 50% female. The interaction term age×female is easy to calculate once we create variables for age and female.

### Step 2: Variable composition

Specify the details of the covariates, such as the range of age or the proportion of females.

Let's assume that we will measure the children's weight every 4 months for 4 years beginning at age 10. Also, in the sample, the proportion of female is equal to that of male. It's not difficult to calculate the iteration term when generate the variable for age and female.

### Step 3: Parameter composition

Locate or think about reasonable values for the parameters in your model. In this step, we use an external data set measuring Asian kid's data to estimate the coefficients for the above regression model, and we get $\beta_0=5.35$, $\beta_1=3.59$, $\beta_2=-0.47$, $\beta_3=-0.24$, $\tau_0=0.24$, $\tau_1=-0.57$ and $\sigma=1.17$.
